[package]
name = "stm32f030r8-nucleo-tests"
version = "0.1.0"
authors = ["Sergey Matyukevich <geomatsi@gmail.com>"]

[dependencies]
cortex-m = "0.5.4"
cortex-m-rt = "0.5.2"
panic-semihosting = "0.3.0"
cortex-m-semihosting = "0.3.0"

[dependencies.stm32f0]
version = "0.2.2"
features = ["stm32f0x0", "rt"]
